// test/rng/test_rng_corpus_msg.cpp — #878 message-vocabulary parity gate:
// the engine's per-error messages must match the Jing reference text
// (after stripping the "path:line:col: error: " prefix).
//
// Same corpus as test_rng_corpus.cpp; we load jing-ref.json to get
// the exact "error: ..." strings Jing emitted and assert the engine
// produces them (1:1, in order) for every bad case.
//
// Public API only — black-box gate, no rng_internal.h.

#include <gtest/gtest.h>

#include "leptris.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#ifndef LEPTRIS_RNG_CASES_DIR
#define LEPTRIS_RNG_CASES_DIR "test/rng/jing-cases"
#endif

namespace {

std::string slurp(const std::string& path) {
    std::ifstream f(path);
    if (!f) return "";
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

/* Minimal JSON parser for jing-ref.json (only strings + objects). */
struct RefEntry {
    int rc;
    std::string out;     /* multi-line, each "path:line:col: error: ..." */
};

static std::string strip_path(const std::string& line) {
    /* "001.bad.xml:1:11: error: ..." -> "error: ..." */
    auto p = line.find("error: ");
    if (p == std::string::npos) return line;
    return line.substr(p);
}

bool load_ref(const std::string& path,
              std::vector<std::pair<std::string, RefEntry>>& outv) {
    std::string s = slurp(path);
    if (s.empty()) return false;
    /* Walk lines; we don't need a full JSON parser because the
     * file is generated by us and uses a stable shape. */
    size_t i = 0;
    while (i < s.size()) {
        /* Find a key "NNN.ok" or "NNN.bad". */
        size_t q1 = s.find('"', i);
        if (q1 == std::string::npos) break;
        size_t q2 = s.find('"', q1 + 1);
        if (q2 == std::string::npos) break;
        std::string key = s.substr(q1 + 1, q2 - q1 - 1);
        size_t dot = key.rfind('.');
        bool is_case = dot != std::string::npos &&
                       (key.substr(dot + 1) == "ok" ||
                        key.substr(dot + 1) == "bad");
        if (!is_case) { i = q2 + 1; continue; }
        size_t ob = s.find('{', q2);
        if (ob == std::string::npos) break;
        size_t cb = s.find('}', ob);
        if (cb == std::string::npos) break;
        std::string body = s.substr(ob + 1, cb - ob - 1);
        RefEntry e{0, ""};
        size_t rc_p = body.find("\"rc\":");
        if (rc_p != std::string::npos) {
            e.rc = std::atoi(body.c_str() + rc_p + 5);
        }
        size_t out_p = body.find("\"out\":");
        if (out_p != std::string::npos) {
            size_t qs = body.find('"', out_p + 6);
            if (qs != std::string::npos) {
                /* Find the real closing quote — skip \" escapes. */
                size_t qe = qs + 1;
                while (qe < body.size()) {
                    if (body[qe] == '\\') { qe += 2; continue; }
                    if (body[qe] == '"') break;
                    qe++;
                }
                if (qe < body.size()) {
                    e.out = body.substr(qs + 1, qe - qs - 1);
                    /* Unescape \n and \" (the file uses no others). */
                    std::string unesc;
                    for (size_t k = 0; k < e.out.size(); k++) {
                        if (e.out[k] == '\\' && k + 1 < e.out.size()) {
                            char nxt = e.out[k + 1];
                            if (nxt == 'n') { unesc.push_back('\n'); k++; }
                            else if (nxt == '"') { unesc.push_back('"'); k++; }
                            else unesc.push_back(e.out[k]);
                        } else {
                            unesc.push_back(e.out[k]);
                        }
                    }
                    e.out = unesc;
                }
            }
        }
        outv.emplace_back(key, e);
        i = cb + 1;
    }
    return true;
}

/* Split a "path:line:col: error: msg" line and pull out the
    // post-error message. */
std::string message_only(const std::string& line) {
    auto p = line.find("error: ");
    if (p == std::string::npos) return line;
    return line.substr(p + 7);
}

TEST(RngCorpusMessages, MatchesJingMessageText) {
    std::vector<std::pair<std::string, RefEntry>> refs;
    ASSERT_TRUE(load_ref(std::string(LEPTRIS_RNG_CASES_DIR) +
                             "/jing-ref.json",
                         refs))
        << "could not read jing-ref.json";

    int cases = 0;
    int matches = 0;
    for (const auto& kv : refs) {
        const std::string& key = kv.first;
        /* Only bad cases have messages. */
        if (key.find(".bad") == std::string::npos) continue;
        cases++;
        const RefEntry& ref = kv.second;
        if (ref.out.empty()) continue;  /* Jing had no message */

        /* Split ref.out on \n — Jing emits multiple errors per case. */
        std::vector<std::string> expected;
        std::string cur;
        for (char c : ref.out) {
            if (c == '\n') { if (!cur.empty()) expected.push_back(cur); cur.clear(); }
            else cur.push_back(c);
        }
        if (!cur.empty()) expected.push_back(cur);

        /* Strip the path prefix off each expected message. */
        for (auto& m : expected) m = message_only(m);

        /* Schema + instance paths from the key stem (e.g. "003.bad"). */
        std::string stem = key.substr(0, key.find('.'));
        std::string dir = LEPTRIS_RNG_CASES_DIR;
        std::string sch_text = slurp(dir + "/" + stem + ".rng");
        std::string ins_text = slurp(dir + "/" + stem + ".bad.xml");
        ASSERT_FALSE(sch_text.empty()) << stem;
        ASSERT_FALSE(ins_text.empty()) << stem;

        LeptrisStatus st = LEPTRIS_OK;
        LeptrisRelaxNG rng = leptris_rng_parse(
            sch_text.data(), sch_text.size(), &st);
        ASSERT_NE(rng, nullptr) << stem << " parse failed: " << st;
        LeptrisDocument d = leptris_parse_string(
            ins_text.data(), ins_text.size(), &st);
        ASSERT_NE(d, nullptr) << stem << " instance parse failed";

        int valid = leptris_rng_validate(rng, d);
        ASSERT_EQ(valid, 0) << stem << " should be invalid";

        size_t got = leptris_rng_error_count(rng);
        if (got != expected.size()) {
            ADD_FAILURE() << stem << ": expected " << expected.size()
                          << " errors, got " << got;
            for (size_t k = 0; k < got && k < 3; k++)
                ADD_FAILURE() << "  leptris[" << k << "]: "
                              << (leptris_rng_error_message(rng, k)
                                      ? leptris_rng_error_message(rng, k)
                                      : "");
        }
        bool ok = true;
        for (size_t i = 0; i < got && i < expected.size(); i++) {
            const char* msg = leptris_rng_error_message(rng, i);
            std::string m = msg ? msg : "";
            if (m != expected[i]) {
                ADD_FAILURE() << stem << " message[" << i
                              << "] mismatch:\n  jing:    " << expected[i]
                              << "\n  leptris: " << m;
                ok = false;
            }
        }
        if (ok) matches++;

        leptris_document_free(d);
        leptris_rng_free(rng);
    }
    /* Non-vacuous: all 19 bad cases must have been visited. */
    ASSERT_GT(cases, 0);
    EXPECT_EQ(matches, cases) << "cases=" << cases << " matches=" << matches;
}

}  // namespace