#!/usr/bin/env python3
"""Generate src/leptris/xpath/ducet_table.h from vendor/ducet/allkeys.txt.

Parses the Unicode DUCET (allkeys.txt) into flat C arrays:

  ducet_cp[]    codepoints of single-character mappings, sorted
                (binary search); the weight span of entry i is
                [ducet_ce_off[i], ducet_ce_off[i+1]) — offsets are
                sequential, so no per-entry count is needed.
  ducet_ct_*    multi-codepoint mappings (DUCET's few contractions),
                sorted by (a, b, c); c == 0 marks a 2-cp mapping.
                Parallel n_ce because contraction entries append to
                the shared weight pool out of single-cp order.
  ducet_w[]     flat [primary, secondary, tertiary] uint16 triples.

Regenerate after vendoring a new allkeys.txt:
    python3 tools/gen_ducet_table.py > src/leptris/xpath/ducet_table.h
"""

import re
import sys

ALLKEYS = "vendor/ducet/allkeys.txt"
OUT = sys.stdout

CE_RE = re.compile(
    r"\[([\.\*])([0-9A-Fa-f]{4})\.([0-9A-Fa-f]{4})\.([0-9A-Fa-f]{4})\]"
)


def parse():
    single = []  # (cp, [(p, s, t, var), ...])
    contr = []  # (tuple(cps), [(p, s, t, var), ...])
    with open(ALLKEYS, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("@"):
                continue
            lhs, sep, rhs = line.partition(";")
            if not sep:
                continue
            cps = tuple(int(x, 16) for x in lhs.split())
            ces = [
                (int(p, 16), int(s, 16), int(t, 16), star == "*")
                for star, p, s, t in CE_RE.findall(rhs)
            ]
            if not cps or not ces:
                continue
            if len(cps) == 1:
                single.append((cps[0], ces))
            else:
                contr.append((cps, ces))
    return single, contr


def emit_arr(name, fmt, vals, per_line):
    OUT.write(f"static const {fmt[0]} {name}[{len(vals)}] = {{\n")
    for i in range(0, len(vals), per_line):
        OUT.write("    " + ",".join(fmt[1] % v for v in vals[i:i + per_line]) + ",\n")
    OUT.write("};\n")


def main():
    single, contr = parse()
    single.sort(key=lambda e: e[0])
    contr.sort(key=lambda e: e[0])

    weights = []
    varbits = []
    offs = []
    for cp, ces in single:
        offs.append(len(weights) // 3)
        for p, s, t, var in ces:
            weights.extend((p, s, t))
            varbits.append(1 if var else 0)
    total_single_ces = len(weights) // 3

    ct_a, ct_b, ct_c, ct_off, ct_nce = [], [], [], [], []
    for cps, ces in contr:
        ct_a.append(cps[0])
        ct_b.append(cps[1])
        ct_c.append(cps[2] if len(cps) > 2 else 0)
        ct_off.append(len(weights) // 3)
        ct_nce.append(len(ces))
        for p, s, t, var in ces:
            weights.extend((p, s, t))
            varbits.append(1 if var else 0)

    OUT.write("/* Generated by tools/gen_ducet_table.py from DUCET "
              "allkeys.txt — DO NOT EDIT.\n")
    OUT.write(" * Unicode 16.0.0 allkeys; see vendor/ducet/allkeys.txt "
              "(Unicode License).\n")
    OUT.write(" * Single-cp entries: %d; contractions: %d (%d three-cp); "
              "collation elements: %d. */\n"
              % (len(single), len(contr),
                 sum(1 for c in ct_c if c), len(weights) // 3))
    emit_arr("ducet_cp", ("uint32_t", "0x%X"), [cp for cp, _ in single], 8)
    emit_arr("ducet_ce_off", ("uint16_t", "0x%04X"),
             offs + [total_single_ces], 10)
    emit_arr("ducet_ct_a", ("uint32_t", "0x%X"), ct_a, 8)
    emit_arr("ducet_ct_b", ("uint32_t", "0x%X"), ct_b, 8)
    emit_arr("ducet_ct_c", ("uint32_t", "0x%X"), ct_c, 8)
    emit_arr("ducet_ct_off", ("uint16_t", "0x%04X"), ct_off, 10)
    emit_arr("ducet_ct_nce", ("uint8_t", "%d"), ct_nce, 16)
    emit_arr("ducet_w", ("uint16_t", "0x%04X"), weights, 12)
    emit_arr("ducet_var", ("uint8_t", "%d"), varbits, 32)


if __name__ == "__main__":
    main()
